export default [
    "Be what you needed when you were younger.",
    "Be a good role model.",
    "Be confident in your parenting role.",
    "Be willing to learn and grow.",
    "Have patience.",
    "Grow together every day.",
    "Show that your love is unconditional.",
    "Make time for them.",
    "Be flexible.",
    "Tell the truth as compassionately as possible.",
    "Know your own needs and limitations.", 
    "What you do matters.",
    "Adapt your parenting to fit your child.",
    "Show up.",
    "Be involved.",
    "Show interest in their interests.",
    "Foster their independence.",
    "Be consistent.",
    "Lead by example.",
    "Respect parenting differences.",
    "Fess up when you blow it.",
    "Give specific praise.",
    "Give yourself a break.",
    "Don't accept disrespect.",
    "Exercise gratitude.",
    "Say \"I love you\" whenever you feel it, even if it's 743 times a day.",
    "Love your children equally, but treat them uniquely.",
    "Savor the moments.",
    "Inspire your child.",
    "Learn to forgive.",
    "Practice what you preach.",
    "Educate firmly and lovingly.",
]