const BUCKET_NAME = 'nurtue-images';
const REGION = 'us-west-1';
const ACCESSKEYID = 'AKIARHZIOEFA2QK53RTX';
const SECRETACCESSKEY = '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';

export { BUCKET_NAME, REGION, ACCESSKEYID, SECRETACCESSKEY };
  