/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_cognito_identity_pool_id": "us-west-1:142a3382-157c-4c1d-8f8a-58426fa4e6cd",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_wDjAdcDQq",
    "aws_user_pools_web_client_id": "60o426rocdnva5al53mshstj5k",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "nurtue-bucket172437-nurtueenv",
    "aws_user_files_s3_bucket_region": "us-west-1"
};
export default awsmobile;